env:
  global:
    - LC_CTYPE=en_US.UTF-8
    - LANG=en_US.UTF-8

matrix:
  include:
    - os: osx
      osx_image: xcode10.2
      env: PLATFORM="macos" CPU="x64" STABLE="https://github.com/bmx-ng/bmx-ng/releases/download/v0.99.3.31.macos/BlitzMax_macos_0.99.3.31.zip"

install:
  - wget "${STABLE}"
  - unzip "`basename "${STABLE}"`"

script:
  - ./BlitzMax/bin/bmk
    makeapp -a -r -standalone
    -l ${PLATFORM}
    -g ${CPU}
    -o ./bcc
    ./bcc.bmx
  - BUILD_SCRIPT="bcc.console.release.${PLATFORM}.${CPU}.build"
  - chmod +x "./${BUILD_SCRIPT}"
  - ./${BUILD_SCRIPT}

after_success:
  - BCC_VERSION=`./bcc -v | sed 's/^.*\([0-9][0-9]*\.[0-9][0-9]*\).*/\1/'`
  - ZIP_FILENAME="bcc-v${BCC_VERSION}-${PLATFORM}-${CPU}.zip"
  - echo "Zipping $ZIP_FILENAME"
  - zip "$ZIP_FILENAME" bcc
  - echo ZIP_FILENAME > .zip_filename.txt
    # Export the filename because the deploy section cannot access
    # vars from here.

before_deploy:
  - export ZIP_FILENAME=$(cat .zip_filename.txt)

